name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace secret in JS
        run: |
          echo "Replacing secret placeholder in JS..."
          sed -i "s|YOUR_SECRET_PLACEHOLDER|${{ secrets.ABZ5 }}|g" ./path/to/script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./path/to/build
